name: py39_agrefed
channels:
  - conda-forge
dependencies:
  - affine=2.3.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=21.12b0
  - bleach=4.1.0
  - blosc=1.21.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=4.0.0
  - click=8.0.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - cryptography=36.0.1
  - curl=7.81.0
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - double-conversion=3.2.0
  - eigen=3.4.0
  - entrypoints=0.3
  - executing=0.8.2
  - expat=2.4.4
  - ffmpeg=4.3.2
  - fiona=1.8.20
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.28.5
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.4.1
  - geopandas=0.9.0
  - geos=3.10.1
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.3
  - imageio=2.16.0
  - importlib-metadata=4.10.1
  - importlib_resources=5.4.0
  - ipykernel=6.7.0
  - ipython=8.0.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - json-c=0.15
  - jsoncpp=1.9.5
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.2
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.0
  - libcurl=7.81.0
  - libcxx=12.0.1
  - libdap4=3.20.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.4.1
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.70.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm13=13.0.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libogg=1.3.4
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=14.1
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtheora=1.1.1
  - libtiff=4.3.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - loguru=0.5.3
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munch=2.5.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - mysql-common=8.0.28
  - mysql-libs=8.0.28
  - nbclient=0.5.10
  - nbconvert=6.4.1
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - nettle=3.6
  - nltk=3.6.3
  - notebook=6.4.8
  - nspr=4.32
  - nss=3.74
  - numpy=1.22.0
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - owslib=0.25.0
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.17.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.9.0
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.3.1
  - pixman=0.40.0
  - poppler=21.11.0
  - poppler-data=0.4.11
  - postgresql=14.1
  - proj=8.2.1
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.26
  - prompt_toolkit=3.0.26
  - ptyprocess=0.7.0
  - pugixml=1.11.4
  - pure_eval=0.2.1
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.6
  - pyproj=3.3.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.9.10
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyvista=0.33.2
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.12.9
  - qtconsole=5.2.2
  - qtconsole-base=5.2.2
  - qtpy=2.0.0
  - rasterio=1.2.10
  - readline=8.1
  - regex=2021.11.10
  - requests=2.27.1
  - rtree=0.9.7
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - scooby=0.5.11
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=59.8.0
  - shapely=1.8.0
  - six=1.16.0
  - snuggs=1.4.7
  - sqlite=3.37.0
  - stack_data=0.1.3
  - statsmodels=0.13.2
  - tbb=2021.5.0
  - tbb-devel=2021.5.0
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - tiledb=2.5.3
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typed-ast=1.5.1
  - typing_extensions=4.0.1
  - tzcode=2021e
  - tzdata=2021e
  - urllib3=1.26.8
  - utfcpp=3.2.1
  - vtk=9.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - x264=1!161.3030
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.1
  - pip:
    - charset-normalizer==2.0.10
    - coverage==6.2
    - docopt==0.6.2
    - iniconfig==1.1.1
    - itsdangerous==1.1.0
    - p2j==1.3.2
    - pipreqs==0.4.11
    - platformdirs==2.4.1
    - pluggy==1.0.0
    - py==1.11.0
    - pytest==6.2.5
    - pytest-cov==3.0.0
    - toml==0.10.2
    - tomli==1.2.3
    - werkzeug==1.0.1
    - xicor==1.0.1
    - yarg==0.1.9
