# Settings for preprocessing.py

### Input Specifications ###
inpath: '../../../data/Llara/preprocessed/'
outpath: '../../../results/Llara_test/' 
# File name with soil data and corresponding covariates
infname: 'Llara_processed.csv' 


# set project coordinate reference system
project_crs: "EPSG:28355" 

# Name of target for prediction (column name in dataframe)
name_target: 'OC_WB'

# Choose mean function for GP (can be one or a list of mean function), currently implemented:
#'blr': bayesian linear regression with power transformation
#'rf': Random Forest 
mean_functions: ['rf']

### Select minimum and maximum of depth for data selection [in m]
zmin: 0 # minimum depth for prediction (in meters), starting at zero depth to minus zmax 
zmax: 0.1 # 1.5 maximum depth for prediction (in meters), starting at zero depth to minus zmax 

# Name of column for index of test data for Xfold cross-validation (to separate train and test data), only relevant for option 'calc_xval':
name_ixval: 'nfold'

### Name of covariates in soil training data or the cossvalidation data
name_features: ['DEM_30', 'MrVBF', 'MrRTF', 'SlopeDeg', 
'rad_dose', 'rad_u', 'rad_th', 'rad_k', 'silica',
'NDVI_5',  'NDVI_50', 'NDVI_95', 'rain', 'temp',
 'TWI', 'Aspect', 'Soiltype_1', 'Soiltype_2', 'Soiltype_3'] #'gamma_K', 'EM',  'yield', 


