# Settings for featureimportance.py

# output path to save simulated data
outpath: '../synthetic_data/100samples_10features_corramp1/'


###### Model feature specs ######
# number of features:
n_features: 10

# number of important features
n_informative_features: 16

# number of samples
n_samples: 50

# order of the model, either 'linear', 'quadratic', or 'cubic'
model_order: 'quadratic'

# if True, the features are correlated
correlated: False

# random noise level [range: 0-1] that is added to the synthetic data
noise: 0.1

##### Spatial Correlation Specs ######
# spatial correlation length [Gaussian FWHM in arcsec, or in meters if projected crs]
corr_length: 10

# spatial correlation amplitude
corr_amp: 1.0

##### Geospatial Specs ######
# size in x and y direction [in arcsec, or in meters if projected crs]
spatialsize: 100

# [x,y] coordinates of the center of the data in meter (Easting, Northings)    
center: [140,-35]

# coordinate reference system [Default: 'EPSG:4326']
crs: 'EPSG:4326'

# Choose if  grid sampled
grid: True
# if grid = True, specify if samples are drawn from grid 
nsample_from_grid: 100