# Settings for soilmod_xval.py

### Input Specifications ###
inpath: "../../../data/Llara/bars/rescaled_csv/"
outpath: '../../../results/Llara_moisture_2021_xval_spatial/' 
# File name with soil data and corresponding covariates
infname: "Soilmoisture_all_covariates_weekly_2021.csv" 


# set project coordinate reference system
project_crs: "EPSG:28355" 

# Name of target for prediction (column name in dataframe)
name_target: 'D1'

# Name of x (Easting) and y (Northing) coordinate columns
colname_xcoord: 'EASTING'
colname_ycoord: 'NORTHING'

# Choose model function, currently implemented:
#'blr': bayesian linear regression with power transformation
#'rf': Random Forest Regression
#'blr-gp' Gaussian Process with bayesian linear regression as mean function
#'rf-gp' Gaussian Process with random forest regression as mean function
model_functions: ['rf-gp', 'blr-gp']

# Name of column for index of test data for Xfold cross-validation (to separate train and test data), only relevant for option 'calc_xval':
name_ixval: 'nfold'

# Is third dimension of prediction the vertical depth ('vertical') or temporal ('temporal')?
axistype: 'temporal' # 'vertical' # 'temporal'

### If axistype='vertical', select minimum and maximum of depth for data selection [in m]
#colname_zmin: 0 # minimum depth for prediction (in meters), starting at zero depth to minus zmax 
#colname_zmax: 1 # 1.5 maximum depth for prediction (in meters), starting at zero depth to minus zmax 
#colname_zcoord: 'z'

### If axistype='temporal', select minimum and maximum of time for data selection [in m]
colname_tmin: 0 # for > 2022-01-01 ; 2458849.5 # start time for prediction
colname_tmax: 54 # end time for prediction 
colname_tcoord: 'week'


### Name of covariates in soil training data or the cross-validation data
name_features: [
  "AVERAGE-Soil-Temp-10cm", 
  "s2_barest_earth_channel1_mean", 
  "Landscape_Topographic_wetness_index", 
  "TOTAL-Rain-Gauge", 
  "Landscape_Slope_median_300m", 
  "Landscape_MrVBF", 
  "DEM"]

 ## Number of cross-validations:
nfold: 8